server {
    listen 9644 ssl;
    listen [::]:9644 ssl;
    server_name 203.17.177.58;

    ssl_certificate /etc/letsencrypt/live/browser-sync-ip/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/browser-sync-ip/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    client_max_body_size 7m;

    location / {
        proxy_pass http://127.0.0.1:4589;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 80;
    listen [::]:80;
    server_name 203.17.177.58;

    location ^~ /.well-known/acme-challenge/ {
        root /var/lib/browser-sync-acme;
        try_files $uri =404;
    }

    location / {
        return 404;
    }
}
